### ISSUE TITLE
spellcheck: 中文词语纠正需要空格分割

### ISSUE THREAD

**Issue by Dunky-Z** [huacnlee/autocorrect#123]
Hi，遇到两个小问题。版本`v2.5.4`。

1. 如果想要将中文的词语纠正，文本里的词语只有在被空格分割的情况下才会被纠正
      ```
      rules:
        # Auto add spacing between CJK (Chinese, Japanese, Korean) and English words.
        # 0 - off, 1 - error, 2 - warning
        space-word: 1
        # Add space between some punctuations.
        space-punctuation: 1
        # Add space between brackets (), [] when near the CJK.
        space-bracket: 1
        # Convert to fullwidth.
        fullwidth: 1
        # To remove space near the fullwidth punctuations.
        no-space-fullwidth: 1
        # To remove space arouned the fullwidth quotes “”, ''.
        no-space-fullwidth-quote: 1
        # Fullwidth alphanumeric characters to halfwidth.
        halfwidth-word: 1
        # Fullwidth punctuations to halfwidth in english.
        halfwidth-punctuation: 1
        # Spellcheck
        spellcheck: 2
        
      spellcheck:
        mode: 1
        words:
          - 蛋炒饭 = 拉面
      ```
      ```bash
      # 如果这样无法纠正
      我爱吃蛋炒饭加火腿。
      # 这样才会被纠正
      - 我爱吃 蛋炒饭 加火腿。
      + 我爱吃 拉面 加火腿。
      ```
2. 括号后的标点符号不会被纠正
    ```bash
    # 最后的括号是中文括号，加了英文句点，预期结果应该是句点被改为中文句号，但是没有被纠正
    我爱吃蛋炒饭加（火腿）.
     # 英文情况一样，英文括号加中文句号，预期情况句号应该被纠正为句点
     I love (china)。
    ```
