### ISSUE TITLE
vscode configuration file isn't work properly

### ISSUE THREAD

**Issue by oopooa** [huacnlee/autocorrect#214]
The vscode configuration file isn't taking effect in my project. Even though I have specified in the .autocorrectrc file that space-bracket should be 0 to prevent adding spaces between "int" and "[]", the space always reappears when I save the file. This indicates that the configuration file is not working as expected.

## Environments
- OS: windows 10
- VsCode Version: 1.90.2
- AutoCorrect Plugin Version: v2.6.4

## Directory tree
```
temptest
 ├── test.md
 └── .autocorrectrc
```

The .autocorrectrc file is located in the root directory of the project.

### test.md
```
int [] nums = [1, 5, 7, 11], 循环三次的 map 结果是 {1 = 0, 5 = 1, 7 = 2}
```

### .autocorrectrc
```yaml
rules:
  # Auto add spacing between CJK (Chinese, Japanese, Korean) and English words.
  # 0 - off, 1 - error, 2 - warning
  space-word: 1
  # Add space between some punctuations.
  space-punctuation: 1
  # Add space between brackets (), [] when near the CJK.
  space-bracket: 0
```
## Troubleshooting Steps Taken
1. restarted vscode, not work.
2. attempted to reload window using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>, not work.

Is there something I missed in order to make the configuration work properly?
