### ISSUE TITLE
Support pre-commit hook

### ISSUE THREAD

**Issue by kwanhur** [huacnlee/autocorrect#23]
Under [pre-commit](http://pre-commit.com/), it can add custom hook. So hope `autocorrect` could support it.

For example, add `.pre-commit-hooks.yaml` in this repo, then users could import it locally in `.pre-commit-config.yaml`.

- *.pre-commit-hooks.yaml*

```yaml
-   id: autocorrect-lint
    name: autocorrect lint
    description: "Checks CJK files' copywriting"
    entry: autocorrect --lint
    language: rust
-   id: autocorrect-fix
    name: autocorrect fix
    description: "Fixes CJK files' copywriting"
    entry: autocorrect --fix
    language: rust
```

- *.pre-commit-config.yaml*

```yaml
- repo: https://github.com/huacnlee/autocorrect
  rev: v1.5.7
  hooks:
    - id: autocorrect-lint
    - id: autocorrect-fix
```
